### ISSUE TITLE
bwa/bowtie2 clarification

### ISSUE THREAD

**Issue by zenalapp** [alipirani88/Comparative_Genomics#33]
Day 1 Afternoon, line 38 is a little unclear to me:

"For whole genome or whole exome sequencing data: Use BWA for long reads (> 50/100 bp), use Bowtie2 for short reads (< 50/100bp)"

What do you mean by 50/100bp? 50 to 100 bp? That seems like a pretty big range. What would you use for 50 bp? 100 bp?

And how long are the reads we're using here when we use BWA to map to KPNIH1? (line 42)

**Comment by alipirani88** [comment]
That means BWA performs well on single end reads that is > 50 bp or PE reads that is >100bp.
whereas, if you have single reads <50bp or PE reads <100bp, use bowtie.

But in practice, both of them yields comparable results. both of them have an improved algorithm now that accommodates different read lengths. 

Our reads are 300 bp long.
