### ISSUE TITLE
index bam file command missing

### ISSUE THREAD

**Issue by zenalapp** [alipirani88/Comparative_Genomics#35]
For day 1 afternoon we sort the bam file but never index it. What's the command for indexing the bam file?

Around line 169

Is this the right command?

`samtools index Rush_KPC_266__aln_sort.bam`

I added this (lines 172 - 175), but please make sure it's right!

**Comment by alipirani88** [comment]
We are indexing it after mark duplicates steps. Also i don't see your changes. May be try making a pull request when making any change so that we can keep record of the changes :)

**Comment by zenalapp** [comment]
Ohh, thanks!
