### ISSUE TITLE
day 1 afternoon - file extension issue 

### ISSUE THREAD

**Issue by sthiede** [alipirani88/Comparative_Genomics#42]
i dont have this file when it is time to run line 503:
Rush_KPC_266__aln_marked.bam.bai

i think its just called .bai not .bam.bai

**Comment by alipirani88** [comment]
We are generating it at line 210

**Comment by sthiede** [comment]
oh that worked so nervermind...but both zena and i ran into this issue the first time....so we must have just both missed it? thanks

**Comment by alipirani88** [comment]
No issues, i am testing day1 afternoon again, so might catch this issue!
